replicaCount: 1

image:
  repository: nginxinc/nginx-unprivileged
  tag: "1.27-alpine"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

message: "Hello World from hello-helm"

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi
