apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
resources:
  - ../../base
labels:
  - pairs:
      app.kubernetes.io/instance: dev
    includeSelectors: true
patches:
  - target:
      kind: Deployment
      name: hello-kustomize
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: |
          echo 'Hello World from hello-kustomize (dev)' > /usr/share/nginx/html/index.html && exec nginx -g 'daemon off;'
